"""Ausgangsschema

Revision ID: 0001
Revises: 
Create Date: 2026-10-07 14:40:21.860903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.common


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campingplatz',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('adresse', sa.String(length=300), nullable=True),
    sa.Column('gemeinde', sa.String(length=100), nullable=True),
    sa.Column('kanton', sa.String(length=50), nullable=True),
    sa.Column('gemeinde_nummer', sa.String(length=20), nullable=True),
    sa.Column('bur_nummer', sa.String(length=20), nullable=True),
    sa.Column('hesta_anzahl_zimmer', sa.Integer(), nullable=True),
    sa.Column('hesta_anzahl_betten', sa.Integer(), nullable=True),
    sa.Column('id', app.models.common.GUID(), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_vorlage',
    sa.Column('typ', sa.String(length=50), nullable=False),
    sa.Column('sprache', sa.String(length=2), nullable=False),
    sa.Column('betreff', sa.String(length=300), nullable=False),
    sa.Column('koerper', sa.Text(), nullable=False),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.Column('zuletzt_geaendert_von', sa.String(length=100), nullable=True),
    sa.Column('id', app.models.common.GUID(), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feratel_konfiguration',
    sa.Column('gemeinde_nummer', sa.String(length=20), nullable=True),
    sa.Column('firmen_nummer', sa.String(length=20), nullable=True),
    sa.Column('endpoint_url', sa.String(length=300), nullable=True),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.common.GUID(), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gast',
    sa.Column('vorname', sa.String(length=100), nullable=False),
    sa.Column('nachname', sa.String(length=100), nullable=False),
    sa.Column('geburtsdatum', sa.Date(), nullable=True),
    sa.Column('nationalitaet', sa.String(length=2), nullable=True),
    sa.Column('plz', sa.String(length=20), nullable=True),
    sa.Column('ort', sa.String(length=100), nullable=True),
    sa.Column('land', sa.String(length=2), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefon', sa.String(length=50), nullable=True),
    sa.Column('id', app.models.common.GUID(), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hesta_meldung',
    sa.Column('monat', sa.Integer(), nullable=False),
    sa.Column('jahr', sa.Integer(), nullable=False),
    sa.Column('generiert_am', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('pdf_pfad', sa.String(length=500), nullable=True),
    sa.Column('schliessungstage', sa.Text(), nullable=True),
    sa.Column('belegte_zimmer', sa.Integer(), nullable=True),
    sa.Column('durchschnittsertrag_pro_logiernacht', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('bemerkung', sa.Text(), nullable=True),
    sa.Column('eingereicht_am', sa.DateTime(timezone=True), nullable=True),
    sa.Column('versandart', sa.String(length=20), nullable=True),
    sa.Column('id', app.models.common.GUID(), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mailchimp_konfiguration',
    sa.Column('api_key_verschluesselt', sa.Text(), nullable=True),
    sa.Column('server_prefix', sa.String(length=10), nullable=True),
    sa.Column('audience_id', sa.String(length=50), nullable=True),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.Column('webhook_url', sa.String(length=300), nullable=True),
    sa.Column('id', app.models.common.GUID(), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mwstsatz',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('bezeichnung', sa.String(length=100), nullable=False),
    sa.Column('satz_prozent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('gueltig_ab', sa.Date(), nullable=False),
    sa.Column('gueltig_bis', sa.Date(), nullable=True),
    sa.Column('id', app.models.common.GUID(), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mwstsatz_code'), 'mwstsatz', ['code'], unique=False)
    op.create_table('newsletter_abo',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('vorname', sa.String(length=100), nullable=True),
    sa.Column('sprache', sa.String(length=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('einwilligung_am', sa.DateTime(timezone=True), nullable=True),
    sa.Column('einwilligung_quelle', sa.String(length=50), nullable=True),
    sa.Column('abgemeldet_am', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mailchimp_member_id', sa.String(length=100), nullable=True),
    sa.Column('mailchimp_sync_status', sa.String(length=20), nullable=False),
    sa.Column('id', app.models.common.GUID(), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newsletter_abo_email'), 'newsletter_abo', ['email'], unique=True)
    op.create_table('newsletter_kampagne',
    sa.Column('titel', sa.String(length=200), nullable=False),
    sa.Column('sprache', sa.String(length=2), nullable=False),
    sa.Column('betreff', sa.String(length=300), nullable=False),
    sa.Column('inhalt', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('geplant_am', sa.DateTime(timezone=True), nullable=True),
    sa.Column('versendet_am', sa.DateTime(timezone=True), nullable=True),
    sa.Column('erstellt_von', sa.String(length=100), nullable=True),
    sa.Column('mailchimp_campaign_id', sa.String(length=100), nullable=True),
    sa.Column('id', app.models.common.GUID(), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rechnungsnummernzaehler',
    sa.Column('jahr', sa.Integer(), nullable=False),
    sa.Column('letzte_vergebene_nummer', sa.Integer(), nullable=False),
    sa.Column('id', app.models.common.GUID(), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jahr', name='uq_rechnungsnummernzaehler_jahr')
    )
    op.create_table('reservationsanfrage',
    sa.Column('quelle', sa.String(length=30), nullable=False),
    sa.Column('eingangs_datum', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sprache', sa.String(length=2), nullable=False),
    sa.Column('mail_message_id', sa.String(length=255), nullable=True),
    sa.Column('gast_name', sa.String(length=200), nullable=False),
    sa.Column('gast_email', sa.String(length=255), nullable=False),
    sa.Column('gast_telefon', sa.String(length=50), nullable=True),
    sa.Column('gewuenscht_von', sa.Date(), nullable=True),
    sa.Column('gewuenscht_bis', sa.Date(), nullable=True),
    sa.Column('stellplatz_typ', sa.String(length=50), nullable=True),
    sa.Column('anzahl_erwachsene', sa.Integer(), nullable=False),
    sa.Column('anzahl_kinder', sa.Integer(), nullable=False),
    sa.Column('bemerkung', sa.Text(), nullable=True),
    sa.Column('rohtext', sa.Text(), nullable=True),
    sa.Column('vollstaendig', sa.Boolean(), nullable=False),
    sa.Column('fehlende_angaben', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('newsletter_einwilligung', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.common.GUID(), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mail_message_id')
    )
    op.create_table('saison',
    sa.Column('bezeichnung', sa.String(length=100), nullable=False),
    sa.Column('gueltig_ab', sa.Date(), nullable=False),
    sa.Column('gueltig_bis', sa.Date(), nullable=False),
    sa.Column('id', app.models.common.GUID(), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taxensatz',
    sa.Column('typ', sa.String(length=50), nullable=False),
    sa.Column('gueltig_ab', sa.Date(), nullable=False),
    sa.Column('gueltig_bis', sa.Date(), nullable=True),
    sa.Column('altersgruppe_von', sa.Integer(), nullable=True),
    sa.Column('altersgruppe_bis', sa.Integer(), nullable=True),
    sa.Column('betrag_pro_nacht', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('gemeinde_oder_kanton', sa.String(length=50), nullable=False),
    sa.Column('id', app.models.common.GUID(), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zahlungsanbieterkonfiguration',
    sa.Column('zahlungsart', sa.String(length=30), nullable=False),
    sa.Column('anbieter', sa.String(length=100), nullable=True),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.Column('zugangsdaten_verschluesselt', sa.Text(), nullable=True),
    sa.Column('webhook_url', sa.String(length=300), nullable=True),
    sa.Column('id', app.models.common.GUID(), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artikel',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('bezeichnung', sa.String(length=150), nullable=False),
    sa.Column('kategorie', sa.String(length=50), nullable=False),
    sa.Column('einheit', sa.String(length=30), nullable=False),
    sa.Column('mwstsatz_id', app.models.common.GUID(), nullable=False),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.common.GUID(), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mwstsatz_id'], ['mwstsatz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artikel_code'), 'artikel', ['code'], unique=True)
    op.create_table('email_versand',
    sa.Column('bezug_typ', sa.String(length=30), nullable=False),
    sa.Column('bezug_id', app.models.common.GUID(), nullable=False),
    sa.Column('vorlage_id', app.models.common.GUID(), nullable=False),
    sa.Column('gesendet_von', sa.String(length=100), nullable=False),
    sa.Column('empfaenger', sa.String(length=255), nullable=False),
    sa.Column('betreff_final', sa.String(length=300), nullable=False),
    sa.Column('koerper_final', sa.Text(), nullable=False),
    sa.Column('anhang_pfad', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('gesendet_am', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', app.models.common.GUID(), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vorlage_id'], ['email_vorlage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hesta_meldung_position',
    sa.Column('hesta_meldung_id', app.models.common.GUID(), nullable=False),
    sa.Column('land', sa.String(length=2), nullable=False),
    sa.Column('anzahl_personen', sa.Integer(), nullable=False),
    sa.Column('anzahl_uebernachtungen', sa.Integer(), nullable=False),
    sa.Column('id', app.models.common.GUID(), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hesta_meldung_id'], ['hesta_meldung.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('newsletter_versand',
    sa.Column('kampagne_id', app.models.common.GUID(), nullable=False),
    sa.Column('newsletter_abo_id', app.models.common.GUID(), nullable=False),
    sa.Column('gesendet_am', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('abmeldelink_verwendet_am', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.models.common.GUID(), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['kampagne_id'], ['newsletter_kampagne.id'], ),
    sa.ForeignKeyConstraint(['newsletter_abo_id'], ['newsletter_abo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zahlung',
    sa.Column('bezug_typ', sa.String(length=30), nullable=False),
    sa.Column('bezug_id', app.models.common.GUID(), nullable=False),
    sa.Column('betrag', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('waehrung', sa.String(length=3), nullable=False),
    sa.Column('zahlungsart', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('referenz', sa.String(length=100), nullable=True),
    sa.Column('eingegangen_am', sa.DateTime(timezone=True), nullable=True),
    sa.Column('abgeglichen_von', sa.String(length=100), nullable=True),
    sa.Column('zahlungsanbieterkonfiguration_id', app.models.common.GUID(), nullable=True),
    sa.Column('id', app.models.common.GUID(), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['zahlungsanbieterkonfiguration_id'], ['zahlungsanbieterkonfiguration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artikel_preis',
    sa.Column('artikel_id', app.models.common.GUID(), nullable=False),
    sa.Column('saison_id', app.models.common.GUID(), nullable=True),
    sa.Column('preis', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('id', app.models.common.GUID(), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artikel_id'], ['artikel.id'], ),
    sa.ForeignKeyConstraint(['saison_id'], ['saison.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stellplatz',
    sa.Column('campingplatz_id', app.models.common.GUID(), nullable=False),
    sa.Column('bezeichnung', sa.String(length=100), nullable=False),
    sa.Column('typ', sa.String(length=50), nullable=False),
    sa.Column('max_personen', sa.Integer(), nullable=True),
    sa.Column('strom_anschluss', sa.Boolean(), nullable=False),
    sa.Column('artikel_id', app.models.common.GUID(), nullable=True),
    sa.Column('id', app.models.common.GUID(), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artikel_id'], ['artikel.id'], ),
    sa.ForeignKeyConstraint(['campingplatz_id'], ['campingplatz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('buchung',
    sa.Column('stellplatz_id', app.models.common.GUID(), nullable=False),
    sa.Column('von', sa.Date(), nullable=False),
    sa.Column('bis', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('hauptgast_id', app.models.common.GUID(), nullable=False),
    sa.Column('reservationsanfrage_id', app.models.common.GUID(), nullable=True),
    sa.Column('id', app.models.common.GUID(), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hauptgast_id'], ['gast.id'], ),
    sa.ForeignKeyConstraint(['reservationsanfrage_id'], ['reservationsanfrage.id'], ),
    sa.ForeignKeyConstraint(['stellplatz_id'], ['stellplatz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aufenthalt',
    sa.Column('buchung_id', app.models.common.GUID(), nullable=False),
    sa.Column('gast_id', app.models.common.GUID(), nullable=False),
    sa.Column('ankunft', sa.Date(), nullable=False),
    sa.Column('abreise', sa.Date(), nullable=False),
    sa.Column('taxpflichtig', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.common.GUID(), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buchung_id'], ['buchung.id'], ),
    sa.ForeignKeyConstraint(['gast_id'], ['gast.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rechnung',
    sa.Column('buchung_id', app.models.common.GUID(), nullable=False),
    sa.Column('kunde_id', app.models.common.GUID(), nullable=False),
    sa.Column('nummer', sa.String(length=20), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('gesamtbetrag', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('mwst_betrag_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pdf_pfad', sa.String(length=500), nullable=True),
    sa.Column('versendet_am', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.models.common.GUID(), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buchung_id'], ['buchung.id'], ),
    sa.ForeignKeyConstraint(['kunde_id'], ['gast.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rechnung_nummer'), 'rechnung', ['nummer'], unique=True)
    op.create_table('feratel_meldung',
    sa.Column('aufenthalt_id', app.models.common.GUID(), nullable=False),
    sa.Column('gesendet_am', sa.DateTime(timezone=True), nullable=True),
    sa.Column('xml_payload', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('fehlercode', sa.String(length=50), nullable=True),
    sa.Column('antwort_roh', sa.Text(), nullable=True),
    sa.Column('id', app.models.common.GUID(), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aufenthalt_id'], ['aufenthalt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rechnungsposition',
    sa.Column('rechnung_id', app.models.common.GUID(), nullable=False),
    sa.Column('artikel_id', app.models.common.GUID(), nullable=False),
    sa.Column('menge', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('einzelpreis', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('betrag', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('mwstsatz_prozent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('mwst_betrag', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', app.models.common.GUID(), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artikel_id'], ['artikel.id'], ),
    sa.ForeignKeyConstraint(['rechnung_id'], ['rechnung.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rechnungsposition')
    op.drop_table('feratel_meldung')
    op.drop_index(op.f('ix_rechnung_nummer'), table_name='rechnung')
    op.drop_table('rechnung')
    op.drop_table('aufenthalt')
    op.drop_table('buchung')
    op.drop_table('stellplatz')
    op.drop_table('artikel_preis')
    op.drop_table('zahlung')
    op.drop_table('newsletter_versand')
    op.drop_table('hesta_meldung_position')
    op.drop_table('email_versand')
    op.drop_index(op.f('ix_artikel_code'), table_name='artikel')
    op.drop_table('artikel')
    op.drop_table('zahlungsanbieterkonfiguration')
    op.drop_table('taxensatz')
    op.drop_table('saison')
    op.drop_table('reservationsanfrage')
    op.drop_table('rechnungsnummernzaehler')
    op.drop_table('newsletter_kampagne')
    op.drop_index(op.f('ix_newsletter_abo_email'), table_name='newsletter_abo')
    op.drop_table('newsletter_abo')
    op.drop_index(op.f('ix_mwstsatz_code'), table_name='mwstsatz')
    op.drop_table('mwstsatz')
    op.drop_table('mailchimp_konfiguration')
    op.drop_table('hesta_meldung')
    op.drop_table('gast')
    op.drop_table('feratel_konfiguration')
    op.drop_table('email_vorlage')
    op.drop_table('campingplatz')
    # ### end Alembic commands ###
