"""Strasse des Gastes, Meldescheinnummer

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-07 15:06:22.886280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feratel_meldung', sa.Column('meldescheinnummer', sa.String(length=50), nullable=True))
    op.add_column('gast', sa.Column('strasse', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gast', 'strasse')
    op.drop_column('feratel_meldung', 'meldescheinnummer')
    # ### end Alembic commands ###
